name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACCOUNT_MANAGEMENT_ROLE_ARN: "${{ secrets.ACCOUNT_MANAGEMENT_ROLE_ARN }}"
      ACCOUNT_1_ROLE_ARN: "${{ secrets.ACCOUNT_1_ROLE_ARN }}"
      TF_VAR_destination_account_id: ${{ secrets.DESTINATION_ACCOUNT_ID }}
      TF_VAR_destination_bucket_name: ${{ secrets.DESTINATION_BUCKET_NAME }}
      TF_VAR_source_account_list: ${{ secrets.SOURCE_ACCOUNT_LIST }}
      TF_VAR_schedule: ${{ vars.SCHEDULE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 全履歴を取得
          submodules: 'recursive'  # サブモジュールも取得

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.3

      - name: Configure AWS Credentials(AccountManagement)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ACCOUNT_MANAGEMENT_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Terraform Apply(AccountManagement)
        run: |
          cd environments/AccountManagement
          terraform init -reconfigure
          terraform apply -auto-approve
          
      - name: Configure AWS Credentials(Account1)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ACCOUNT_1_ROLE_ARN }}
          aws-region: ap-northeast-1
          
      - name: Terraform Apply(Account1)
        run: |
          cd environments/Account1
          terraform init -reconfigure
          terraform apply -auto-approve
          
